linters-settings:
  lll:
    line-length: 140

linters:
  enable-all: true
  disable:
    - bodyclose
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
