coverage:
  status:
    project:
      default:
        target: 85%
        flags: core
      pb:
        target: 75%
        flags: pb
    patch: off

flags:
  core:
    paths:
      - '!pb/'
  pb:
    paths:
      - 'pb/'
