coverage:
  status:
    project:
      default: off
      core:
        target: 85%
        flags: core
      plugins.pb:
        target: 70%
        flags: plugins.pb
      plugins.retry:
        target: 70%
        flags: plugins.retry
    patch: off

flags:
  core:
    paths:
      - '!plugins/'
  plugins.pb:
    paths:
      - 'plugins/pb/'
    joined: false
  plugins.retry:
    paths:
      - 'plugins/retry/'
    joined: false
