coverage:
  status:
    project:
      default:
        target: 85%
        paths:
          - '!plugins/'
      pb:
        target: 70%
        flags: pb
      retry:
        target: 70%
        flags: retry
    patch: off

flags:
  pb:
    paths:
      - 'plugins/pb/'
    joined: false
  retry:
    paths:
      - 'plugins/retry/'
    joined: false
