coverage:
  status:
    project:
      default:
        target: 85%
        paths:
          - '!pb/'
      pb:
        target: 75%
        flags: pb
    patch: off

flags:
  pb:
    paths:
      - 'pb/'
    joined: false
