coverage:
  status:
    project:
      default: off
      core:
        target: 85%
        flags: core
      plugins.hxlog:
        target: 70%
        flags: plugins.hxlog
      plugins.hxzap:
        target: 70%
        flags: plugins.hxzap
      plugins.pb:
        target: 70%
        flags: plugins.pb
      plugins.retry:
        target: 70%
        flags: plugins.retry
    patch: off

flags:
  core:
    paths:
      - '!plugins/'
  plugins.hxlog:
    paths:
      - 'plugins/hxlog/'
    joined: false
  plugins.hxzap:
    paths:
      - 'plugins/hxzap/'
    joined: false
  plugins.pb:
    paths:
      - 'plugins/pb/'
    joined: false
  plugins.retry:
    paths:
      - 'plugins/retry/'
    joined: false
