coverage:
  status:
    project:
      default:
        target: 85%
        paths:
          - '!pb/'
          - '!retry/'
      pb:
        target: 70%
        flags: pb
      retry:
        target: 70%
        flags: retry
    patch: off

flags:
  pb:
    paths:
      - 'pb/'
    joined: false
  retry:
    paths:
      - 'retry/'
    joined: false
