coverage:
  status:
    project:
      default: off
      core:
        target: 85%
        flags: core
      plugins.hxlog:
        target: 70%
        flags: hxlog
      plugins.hxzap:
        target: 70%
        flags: hxzap
      plugins.pb:
        target: 70%
        flags: pb
      plugins.retry:
        target: 70%
        flags: retry
    patch: off

flags:
  core:
    paths:
      - '!plugins/'
  hxlog:
    paths:
      - 'plugins/hxlog/'
    joined: false
  hxzap:
    paths:
      - 'plugins/hxzap/'
    joined: false
  pb:
    paths:
      - 'plugins/pb/'
    joined: false
  retry:
    paths:
      - 'plugins/retry/'
    joined: false
