name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.12.x', '1.13.x']
      fail-fast: false

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
 
    - uses: actions/checkout@v1

    - run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

    - uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: core

  test-plugins:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.13.x']
        module: ['pb', 'retry']
      fail-fast: false

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v1

    - run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...
      working-directory: ./plugins/${{ matrix.module }}

    - uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: plugins.${{ matrix.module }}
        file: ./plugins/${{ matrix.module }}/coverage.txt
