name: CI
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.12.x', '1.13.x']
        module: ['core', 'pb']
      fail-fast: false

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
 
    - uses: actions/checkout@v1

    # for core modules
    - run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...
      if: matrix.module == 'core'

    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: 'core'
      if: matrix.go-version == '1.13.x' && matrix.module == 'core'

    # for submodules
    - run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...
      working-directory: ${{ matrix.module }}
      if: matrix.module != 'core'

    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.module }}
        file: ./${{ matrix.module }}/coverage.txt
      if: matrix.go-version == '1.13.x' && matrix.module != 'core'
